version: "3"
services:
  app:
    container_name: express-pic2prod
    restart: always
    build: ./
    ports:
      - "80:3000"
    volumes:
      - .:/app
    links:
      - mongo
  
  mongo:
    container_name: mongo-pic2prod
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
      
volumes:
  mongodb:
  mongodb_config:
