version: "3"
services:
  app:
    container_name: express-pic2prod
    restart: always
    build: ./
    volumes:
      - .:/app
    links:
      - mongo
    networks:
      - app-network

  nginx:
    image: nginx:mainline-alpine
    container_name: nginx-pic2prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot-pic2prod
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email kriscarilloxyz@gmail.com --agree-tos --no-eff-email --force-renewal -d pic2prod.com
      
  mongo:
    container_name: mongo-pic2prod
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb:
  mongodb_config:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/kris/Repos/pic2rod/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: home/kris/Repos/pic2rod/dhparam
      o: bind

networks:
  app-network:
    driver: bridge